# Generated by Django 4.2 on 2023-04-17 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bitches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bitch",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterField(
            model_name="bitch",
            name="image",
            field=models.ImageField(upload_to="bitches/%Y/%m/%d/"),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photo", models.FileField(upload_to="images/%Y/%m/%d/")),
                ("is_preview", models.BooleanField(default=False)),
                (
                    "bitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bitches.bitch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фотки",
            },
        ),
    ]
