# Generated by Django 4.2 on 2023-04-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bitches", "0004_alter_bitch_id_alter_category_id_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="bitches.category",
                verbose_name="Родительская категория",
            ),
        ),
    ]
