# Generated by Django 4.2 on 2023-04-24 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bitches", "0005_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitch",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
