# Generated by Django 4.2 on 2023-04-17 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(max_length=60, verbose_name="номер телефона"),
                ),
                (
                    "typee",
                    models.CharField(
                        choices=[("PRODUSER", "Produser"), ("CONSUMER", "Consumer")],
                        default="CONSUMER",
                        max_length=10,
                        verbose_name="Тип пользователя",
                    ),
                ),
                (
                    "geo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="геолокация"
                    ),
                ),
                (
                    "rathing",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Рейтинг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
